# Generated by Django 4.2.7 on 2023-11-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI_auto', '0002_instruction_section_subsection_auto_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='instruction_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendAPI_auto.instruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='instruction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendAPI_auto.instruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='section_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendAPI_auto.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
    ]
