# Generated by Django 4.2.7 on 2023-11-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI_auto', '0003_auto_instruction_id_section_instruction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='instruction_id',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='instruction_id',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='subsection',
            old_name='section_id',
            new_name='section',
        ),
    ]
