# Generated by Django 4.2.7 on 2023-11-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI_auto', '0006_remove_auto_instruction_instruction_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
