# Generated by Django 4.2.7 on 2023-12-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI_auto', '0007_alter_auto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL Section'),
            preserve_default=False,
        ),
    ]
